name: Staging (Pull Request to Main)

on:
  pull_request:
    branches: [main]

# ----- THIS HAS BEEN COMMENTED OUT DUE TO THE FOLLOWING KNOWN BUG:
# https://github.com/github/feedback/discussions/10679
# ----- TEMPORARY WORKAROUND IS TO DUPLICATE WORKFLOW CODE

jobs:
  sonarcloud-scan:
    uses: ./.github/workflows/sonarcloud.yaml
    with:
      ENV: staging
      GO_VERSION: ^1.17.6

  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      ENV: staging
      GO_VERSION: ^1.17.6
