name: Main Pull Request

on:
  pull_request:
    branches:
      - main

# ----- THIS HAS BEEN COMMENTED OUT DUE TO THE FOLLOWING KNOWN BUG:
# https://github.com/github/feedback/discussions/10679
# ----- TEMPORARY WORKAROUND IS TO DUPLICATE WORKFLOW CODE

# jobs:
#   sonarcloud-scan:
#     uses: ./.github/workflows/sonarcloud.yaml
#     with:
#       ENV: staging
#       GO_VERSION: ^1.17.6

env:
  GO_VERSION: ^1.17.6

jobs:
  unit-test:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run the unit tests
        run: make test-unit
        env:
          SAVE_TEST_COVERAGE: true

      - name: Upload unit test data
        uses: actions/upload-artifact@master
        with:
          name: unit-test-results
          path: .coverage/

  sonar-scan:
    environment: staging
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Retrieve unit test data
        uses: actions/download-artifact@master
        with:
          name: unit-test-results
          path: .coverage/

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
