name: CI

on:
  pull_request:
    branches: [main]

jobs:
  sonarcloud-scan:
    environment: staging
    uses: ./.github/workflows/sonarcloud.yaml
    with:
      ENV: staging
      GO_VERSION: ^1.17.6
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
