name: Main Pull Request

on:
  push:
    branches: [main]

# ----- THIS HAS BEEN COMMENTED OUT DUE TO THE FOLLOWING KNOWN BUG:
# https://github.com/github/feedback/discussions/10679
# ----- TEMPORARY WORKAROUND IS TO DUPLICATE WORKFLOW CODE

# jobs:
#   sonarcloud-scan:
#     uses: ./.github/workflows/sonarcloud.yaml
#     with:
#       ENV: production
#       GO_VERSION: ^1.17.6

env:
  GO_VERSION: ^1.17.6

concurrency: production

jobs:
  unit-test:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run the unit tests
        run: make test-unit
        env:
          SAVE_TEST_COVERAGE: true

      - name: Upload unit test data
        uses: actions/upload-artifact@master
        with:
          name: unit-test-results
          path: .coverage/

  sonar-scan:
    environment: production
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Retrieve unit test data
        uses: actions/download-artifact@master
        with:
          name: unit-test-results
          path: .coverage/

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-production:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get Node Package Manager
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Build and deploy the infrastructure
        run: make build-infra deploy-infra
        env:
          AWS_TARGET_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENV: ${{ inputs.ENV }}

  integration-test:
    environment: production
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run the integration tests
        run: make test-integration
